### ISSUE TITLE
Dependencies missing 

### ISSUE THREAD

**Issue by maxfrigge** [cloudinary/pkg-cloudinary-core#1]
Installed the package from npm and compiling with babel.

Getting this error

```
ERROR in ./~/cloudinary-core/cloudinary-core.js
Module not found: Error: Cannot resolve module 'transformation' in /product-editor/node_modules/cloudinary-core
 @ ./~/cloudinary-core/cloudinary-core.js 670:13-80

ERROR in ./~/cloudinary-core/cloudinary-core.js
Module not found: Error: Cannot resolve module 'cloudinary' in /product-editor/node_modules/cloudinary-core
 @ ./~/cloudinary-core/cloudinary-core.js 2021:13-95

ERROR in ./~/cloudinary-core/cloudinary-core.js
Module not found: Error: Cannot resolve module 'tags/imagetag' in /product-editor/node_modules/cloudinary-core
 @ ./~/cloudinary-core/cloudinary-core.js 2190:13-155
```

**Comment by texel** [comment]
Me too, completely unable to use the library via Webpack.

**Comment by michaek** [comment]
This module is not designed to be compatible with webpack, as it expects its in a node environment because module.exports is an object. I was able to load the module in webpack with https://github.com/webpack/script-loader .

The lodash dependency is not built into the file, and I imagine you would need to do something like this if you don't mind exposing globals:

```
import "script!lodash-compat"
import "script!cloudinary-core"
```

**Comment by rlancer** [comment]
This a pretty big issue for React developers ... I would hope that cloudinary rethinks their approach

**Comment by tocker** [comment]
Hi @maxfrigge , @texel, @michaek , @rlancer,

webpack is now supported in version 2.0.6.
Let us know if it works for you!
