### ISSUE TITLE
Any plan for typescript version or typings defintion?

### ISSUE THREAD

**Issue by xinbenlv** [cloudinary/pkg-cloudinary-core#9]
Hi Cloudinary!
Thank you for this awesome product and happy to hear now core is ready to go. I am wondering do you have any plan in providing the typescript version?
Or do you consider typings like this 
https://github.com/DefinitelyTyped/DefinitelyTyped?

Thank you !

**Comment by taragano** [comment]
Hi @xinbenlv,

Thank you for your warm words :)
While releasing a TypeScript version isn't on our road-map, Typed does looks interesting and we will look into it.

Thank you for your feedback.

**Comment by Airswoop1** [comment]
Yeah this is something I'd love to see you guys implement as well.

**Comment by bogacg** [comment]
Since there is now Angular (> v.2.x) implementation, typings is a must , I guess same problem will be shout by React developers too. Without it, development is very difficult.

**Comment by taragano** [comment]
It's on our road-map to add typings, however there's no ETA for this yet.

Having said that, note that our Angular2 SDK is published with typings for the new components and directives, so for the Angular developers we'd recommend to use our Angular2 SDK rather than directly with our JS core package.

**Comment by eitanp461** [comment]
Typescript definition file added in release 2.3.0 of cloudinary_core - https://github.com/cloudinary/cloudinary_js/releases/tag/2.3.0
